import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProviderWrapper from "@/context/AuthProvider";
import QueryWrapper from "@/context/QueryProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jixel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryWrapper>
          <AuthProviderWrapper>
            <Toaster />

            {children}
          </AuthProviderWrapper>
        </QueryWrapper>
      </body>
    </html>
  );
}
